// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(MiniMarketDbContext))]
    partial class MiniMarketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ChiTietHD", b =>
                {
                    b.Property<int>("MaCT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCT"));

                    b.Property<float>("DonGia")
                        .HasColumnType("real");

                    b.Property<float>("GiamGia")
                        .HasColumnType("real");

                    b.Property<int>("HangHoaMaHH")
                        .HasColumnType("int");

                    b.Property<int>("HoaDonMaHD")
                        .HasColumnType("int");

                    b.Property<int>("MaHD")
                        .HasColumnType("int");

                    b.Property<int>("MaHH")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaCT");

                    b.HasIndex("HangHoaMaHH");

                    b.HasIndex("HoaDonMaHD");

                    b.ToTable("ChiTietHD");
                });

            modelBuilder.Entity("Domain.Entities.HangHoa", b =>
                {
                    b.Property<int>("MaHH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHH"));

                    b.Property<float?>("DonGia")
                        .HasColumnType("real");

                    b.Property<float>("GiamGia")
                        .HasColumnType("real");

                    b.Property<string>("Hinh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySX")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLanXem")
                        .HasColumnType("int");

                    b.Property<string>("TenHH")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaHH");

                    b.HasIndex("MaLoai");

                    b.ToTable("HangHoa");
                });

            modelBuilder.Entity("Domain.Entities.HoaDon", b =>
                {
                    b.Property<int>("MaHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHD"));

                    b.Property<string>("DiaChiGiao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaTrangThai")
                        .HasColumnType("int");

                    b.Property<int>("MaUser")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayGiao")
                        .HasColumnType("datetime2");

                    b.Property<float>("PhiVanChuyen")
                        .HasColumnType("real");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThaiMaTrangThai")
                        .HasColumnType("int");

                    b.Property<int?>("UserMaUser")
                        .HasColumnType("int");

                    b.HasKey("MaHD");

                    b.HasIndex("TrangThaiMaTrangThai");

                    b.HasIndex("UserMaUser");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("Domain.Entities.Loai", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaLoai");

                    b.ToTable("Loai");
                });

            modelBuilder.Entity("Domain.Entities.PhanQuyen", b =>
                {
                    b.Property<int>("MaPQ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPQ"));

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<int>("MaTrang")
                        .HasColumnType("int");

                    b.Property<bool>("Sua")
                        .HasColumnType("bit");

                    b.Property<bool>("Them")
                        .HasColumnType("bit");

                    b.Property<int?>("UserMaUser")
                        .HasColumnType("int");

                    b.Property<bool>("Xem")
                        .HasColumnType("bit");

                    b.Property<bool>("Xoa")
                        .HasColumnType("bit");

                    b.HasKey("MaPQ");

                    b.HasIndex("UserMaUser");

                    b.ToTable("PhanQuyen");
                });

            modelBuilder.Entity("Domain.Entities.TonKho", b =>
                {
                    b.Property<int>("MaHH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHH"));

                    b.Property<int?>("HangHoaMaHH")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.HasKey("MaHH");

                    b.HasIndex("HangHoaMaHH");

                    b.ToTable("TonKho");
                });

            modelBuilder.Entity("Domain.Entities.TrangThai", b =>
                {
                    b.Property<int>("MaTrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTrangThai"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaTrangThai");

                    b.ToTable("TrangThai");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("MaUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaUser"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<int>("VaiTro")
                        .HasColumnType("int");

                    b.HasKey("MaUser");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Domain.Entities.ChiTietHD", b =>
                {
                    b.HasOne("Domain.Entities.HangHoa", "HangHoa")
                        .WithMany("ChiTietHDs")
                        .HasForeignKey("HangHoaMaHH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.HoaDon", "HoaDon")
                        .WithMany("ChiTietHDs")
                        .HasForeignKey("HoaDonMaHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangHoa");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("Domain.Entities.HangHoa", b =>
                {
                    b.HasOne("Domain.Entities.Loai", "Loai")
                        .WithMany("HangHoas")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loai");
                });

            modelBuilder.Entity("Domain.Entities.HoaDon", b =>
                {
                    b.HasOne("Domain.Entities.TrangThai", "TrangThai")
                        .WithMany("HoaDons")
                        .HasForeignKey("TrangThaiMaTrangThai");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("HoaDons")
                        .HasForeignKey("UserMaUser");

                    b.Navigation("TrangThai");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.PhanQuyen", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany("PhanQuyens")
                        .HasForeignKey("UserMaUser");
                });

            modelBuilder.Entity("Domain.Entities.TonKho", b =>
                {
                    b.HasOne("Domain.Entities.HangHoa", "HangHoa")
                        .WithMany("TonKhos")
                        .HasForeignKey("HangHoaMaHH");

                    b.Navigation("HangHoa");
                });

            modelBuilder.Entity("Domain.Entities.HangHoa", b =>
                {
                    b.Navigation("ChiTietHDs");

                    b.Navigation("TonKhos");
                });

            modelBuilder.Entity("Domain.Entities.HoaDon", b =>
                {
                    b.Navigation("ChiTietHDs");
                });

            modelBuilder.Entity("Domain.Entities.Loai", b =>
                {
                    b.Navigation("HangHoas");
                });

            modelBuilder.Entity("Domain.Entities.TrangThai", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("PhanQuyens");
                });
#pragma warning restore 612, 618
        }
    }
}
